FROM dpage/pgadmin4
ENV PGADMIN_DEFAULT_EMAIL=admin@admin.com
ENV PGADMIN_DEFAULT_PASSWORD=pass
EXPOSE 80

#dba % docker run --name mydba2 --network mynetwork -itd -p5555:5555 my_db
#dba % docker run -e PGADMIN_DEFAULT_EMAIL=admin@admin.com
