FROM postgres:12.12
ENV POSTGRES_USER=root
ENV POSTGRES_PASSWORD=pass
ENV POSTGRES_DB=web
EXPOSE 5432

#docker run --name mydb -itd -p432:5432 my_db 
#docker network create mynetwork
#docker network ls
###network to conntect db and db-admin